
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200),
    script character varying(1000),
    installed_on timestamp without time zone DEFAULT now(),
    type character varying(255),
    success boolean
);


ALTER TABLE public.flyway_schema_history OWNER TO postgres;

--
-- Name: flyway_schema_history_installed_rank_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.flyway_schema_history_installed_rank_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.flyway_schema_history_installed_rank_seq OWNER TO postgres;

--
-- Name: flyway_schema_history_installed_rank_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.flyway_schema_history_installed_rank_seq OWNED BY public.flyway_schema_history.installed_rank;


--
-- Name: moves_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

CREATE SEQUENCE public.moves_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.moves_id_seq OWNER TO test;

--
-- Name: moves; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.moves (
    move_id integer DEFAULT nextval('public.moves_id_seq'::regclass) NOT NULL,
    move character varying(255) NOT NULL,
    accuracy integer,
    priority integer,
    power integer,
    type character varying(255),
    pokemon_id integer
);


ALTER TABLE public.moves OWNER TO test;

--
-- Name: pokemon; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.pokemon (
    name character varying(255) NOT NULL,
    sprite_id bigint,
    combat_power double precision,
    user_id character varying(255) NOT NULL,
    pokemon_id integer NOT NULL
);


ALTER TABLE public.pokemon OWNER TO test;

--
-- Name: pokemon_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

CREATE SEQUENCE public.pokemon_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.pokemon_id_seq OWNER TO test;

--
-- Name: pokemon_pokemon_id_temp_seq; Type: SEQUENCE; Schema: public; Owner: test
--

CREATE SEQUENCE public.pokemon_pokemon_id_temp_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.pokemon_pokemon_id_temp_seq OWNER TO test;

--
-- Name: pokemon_pokemon_id_temp_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: test
--

ALTER SEQUENCE public.pokemon_pokemon_id_temp_seq OWNED BY public.pokemon.pokemon_id;


--
-- Name: pokemon_stat; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.pokemon_stat (
    base_stat integer NOT NULL,
    id bigint NOT NULL,
    name character varying(255),
    pokemon_id integer
);


ALTER TABLE public.pokemon_stat OWNER TO test;

--
-- Name: pokemon_stat_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.pokemon_stat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pokemon_stat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pokemon_types; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.pokemon_types (
    id bigint NOT NULL,
    name character varying(255),
    pokemon_id integer NOT NULL,
    slot integer NOT NULL
);


ALTER TABLE public.pokemon_types OWNER TO test;

--
-- Name: pokemon_types_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.pokemon_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pokemon_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sprites; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.sprites (
    sprite_id bigint NOT NULL,
    front_default character varying(255),
    back_default character varying(255)
);


ALTER TABLE public.sprites OWNER TO test;

--
-- Name: sprites_sprite_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

CREATE SEQUENCE public.sprites_sprite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.sprites_sprite_id_seq OWNER TO test;

--
-- Name: sprites_sprite_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: test
--

ALTER SEQUENCE public.sprites_sprite_id_seq OWNED BY public.sprites.sprite_id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.users (
    users_id character varying(255) NOT NULL,
    login character varying(255),
    password character varying(255),
    role smallint,
    CONSTRAINT users_role_check CHECK (((role >= 0) AND (role <= 1)))
);


ALTER TABLE public.users OWNER TO test;

--
-- Name: flyway_schema_history installed_rank; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.flyway_schema_history ALTER COLUMN installed_rank SET DEFAULT nextval('public.flyway_schema_history_installed_rank_seq'::regclass);


--
-- Name: pokemon pokemon_id; Type: DEFAULT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.pokemon ALTER COLUMN pokemon_id SET DEFAULT nextval('public.pokemon_pokemon_id_temp_seq'::regclass);


--
-- Name: sprites sprite_id; Type: DEFAULT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.sprites ALTER COLUMN sprite_id SET DEFAULT nextval('public.sprites_sprite_id_seq'::regclass);


--
-- Name: flyway_schema_history flyway_schema_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pkey PRIMARY KEY (installed_rank);


--
-- Name: moves moves_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.moves
    ADD CONSTRAINT moves_pkey PRIMARY KEY (move_id);


--
-- Name: pokemon pokemon_pk; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.pokemon
    ADD CONSTRAINT pokemon_pk PRIMARY KEY (pokemon_id);


--
-- Name: pokemon_stat pokemon_stat_pk; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.pokemon_stat
    ADD CONSTRAINT pokemon_stat_pk PRIMARY KEY (id);


--
-- Name: pokemon_types pokemon_types_pk; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.pokemon_types
    ADD CONSTRAINT pokemon_types_pk PRIMARY KEY (id);


--
-- Name: sprites sprites_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.sprites
    ADD CONSTRAINT sprites_pkey PRIMARY KEY (sprite_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (users_id);


--
-- Name: pokemon_types fk_pokemon; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.pokemon_types
    ADD CONSTRAINT fk_pokemon FOREIGN KEY (pokemon_id) REFERENCES public.pokemon(pokemon_id);


--
-- Name: moves fk_pokemon_id; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.moves
    ADD CONSTRAINT fk_pokemon_id FOREIGN KEY (pokemon_id) REFERENCES public.pokemon(pokemon_id);


--
-- Name: pokemon_stat fk_pokemon_stat_pokemon; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.pokemon_stat
    ADD CONSTRAINT fk_pokemon_stat_pokemon FOREIGN KEY (pokemon_id) REFERENCES public.pokemon(pokemon_id);


--
-- Name: pokemon fk_sprite; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.pokemon
    ADD CONSTRAINT fk_sprite FOREIGN KEY (sprite_id) REFERENCES public.sprites(sprite_id);


--
-- Name: pokemon fk_user_id; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.pokemon
    ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES public.users(users_id);


--
-- PostgreSQL database dump complete
--

